name: snaphunt
description: SnapHunt - Flutter Philippines Hackathon 2019 Entry

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^0.4.0+9

  # realtime db
  cloud_firestore: ^0.12.9+5

  # ml
  firebase_ml_vision: ^0.9.2+2
  image_picker: ^0.6.1+7

  # auth
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7

  # di
  provider: ^3.1.0+1

  # qr
  qr_flutter: ^3.0.1
  flutter_barcode_scanner: ^0.1.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true